kind: Deployment
apiVersion: apps/v1
metadata:
  name: communication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communication-service
  template:
    metadata:
      labels:
        app: communication-service
    spec:
      containers:
        - name: communication-service
          # image: jsdmmicroservicesindotnet.azurecr.io/communication-service:1.0.0
          image: communication-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: communication-service
spec:
  type: LoadBalancer
  ports:
    - name: communication-service
      port: 5001
      targetPort: 80
  selector:
    app: communication-service